services:
  kaliber5.decoder.json_api:
    class: Kaliber5\SerializerBundle\Decoder\JsonApiDecoder

  kaliber5.normalizer.camel_keys:
    class: Kaliber5\SerializerBundle\Normalizer\CamelKeysNormalizer