services:
  kaliber5.decoder.json_api:
    class: Kaliber5\SerializerBundle\Decoder\JsonApiDecoder
    tags:
      - { name: k5.logger.logging }

  kaliber5.normalizer.camel_keys:
    class: Kaliber5\SerializerBundle\Normalizer\CamelKeysNormalizer